COLUMNS:
 id: int
 gender: str
 age: float
 hypertension: int
 heart_disease: int
 ever_married: str
 work_type: str
 Residence_type: str
 avg_glucose_level: float
 bmi: float
 smoking_status: str
 stroke: int
Target:
 stroke: int