Artifacts_root: artifacts

data_ingestion:
 root_url: artifacts/data_ingestion
 source_url: https://github.com/Robin-star-lab/stroke_zip/raw/refs/heads/main/stroke_zip/healthcare-dataset-stroke-data.zip
 local_data_path: artifacts/data_ingestion/data.zip
 unzip_data: artifacts/data_ingestion
 train_data: artifacts/data_ingestion
 test_data: artifacts/data_ingestion



data_evaluation:
 root_url: artifacts/data_evaluation
 data_directory: artifacts\data_ingestion\healthcare-dataset-stroke-data.csv
 validation_status: artifacts/data_evaluation/validation_status.txt



data_transformation:
 root_url: artifacts/data_transfromation
 data_directory: artifacts\data_ingestion\healthcare-dataset-stroke-data.csv
 transform_data_path: artifacts/data_transformation
 preprocessor_path: artifacts/data_transformation



model_trainer:
 root_url: artifacts/model_trainer
 train_data_path: artifacts/data_transformation/train_data.csv
 trained_model: artifacts/model_trainer
 model_name: artifacts/model_trainer

model_evaluation:
 root_url: artifacts/model_evaluation
 evaluation_data: artifacts/data_transformation/test_data.csv
 model_path: artifacts/model_trainer/model.h5




 