Artifacts_root: artifacts

data_ingestion:
 root_url: artifacts/data_ingestion
 source_url: https://github.com/Robin-star-lab/stroke_zip/raw/refs/heads/main/stroke_zip/healthcare-dataset-stroke-data.zip
 local_data_path: artifacts/data_ingestion/data.zip
 unzip_data: artifacts/data_ingestion
 train_data: artifacts/data_ingestion
 test_data: artifacts/data_ingestion



data_evaluation:
 root_url: artifacts/data_evaluation
 data_directory: artifacts\data_ingestion\healthcare-dataset-stroke-data.csv
 validation_status: artifacts/data_evaluation/validation_status.txt
 